# Generated by Django 2.2.1 on 2020-03-09 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 7, 58, 24, 780544)),
            preserve_default=False,
        ),
    ]
