# Generated by Django 2.2.1 on 2020-03-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotcontrol', '0003_auto_20200310_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='most_recent_device',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
