# Generated by Django 3.0.5 on 2020-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotcontrol', '0004_spotifyuser_most_recent_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentCrews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['crew_title'],
            },
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='most_recent_crews',
            field=models.ManyToManyField(to='spotcontrol.RecentCrews'),
        ),
    ]
