# Generated by Django 3.0.5 on 2020-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotcontrol', '0007_auto_20200415_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentcrews',
            name='crew_id',
            field=models.UUIDField(default='6a512b15-7f51-4202-b842-4bf3fdf2ba2b'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recentcrews',
            name='crew_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
